FROM almalinux/9-base:9.5
RUN dnf update -y && \
    dnf install -y epel-release && \
    dnf install -y \
        cmake make zlib-devel openssl-devel fmt-devel \
        gcc gcc-c++ clang && \
    dnf clean all && \
    rm -rf /var/cache/dnf

USER root
WORKDIR /mnt/workspace
RUN ["/bin/bash"]
