FROM almalinux/9-base:9.5
RUN dnf update -y && \
    dnf install -y cmake make checkinstall zlib-devel openssl-devel libfmt-devel gcc gcc-c++ clang && \
    dnf clean all && \
    rm -rf /var/cache/dnf

USER root
WORKDIR /mnt/workspace
RUN ["/bin/bash"]
