FROM ubuntu:24.04
RUN apt-get update && \
    apt-get install -y \
        cmake build-essential checkinstall zlib1g-dev libssl-dev libfmt-dev \
        clang-14 doxygen graphviz && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER root
WORKDIR /mnt/workspace
RUN ["/bin/bash"]
