name: Build Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  BUILD_DEPENDENCIES: cmake build-essential checkinstall zlib1g-dev libssl-dev
  BUILD_DIRECTORY: build

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: ["Debug", "Release"]
        compiler: [
          { c: "gcc-11", cxx: "g++-11", package: "gcc-11 g++-11" },
          { c: "clang-14", cxx: "clang++-14", package: "clang-14" }
        ]
    name: Build & Test ${{ matrix.build-type }} with ${{ matrix.compiler.cxx }}
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} ${{ matrix.compiler.package }}

      - name: Build
        run: |
          cmake -S . -B ${{ env.BUILD_DIRECTORY }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_C_COMPILER=${{ matrix.compiler.c }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}
          cmake --build ${{ env.BUILD_DIRECTORY }} -j10

      - name: Test
        run: cd ${{ env.BUILD_DIRECTORY }} && ctest -j8 -T test --no-compress-output
