name: Build Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  BUILD_DEPENDENCIES: g++ cmake build-essential checkinstall zlib1g-dev libssl-dev
  BUILD_DIRECTORY: build

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [DEBUG, RELEASE]
    name: Build & Test ${{ matrix.build-type }}
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }}

      - name: Build
        run: |
          if [ "${{matrix.build-type}}" == "DEBUG" ]; then
            cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
          else
            cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Release && cmake --build ${{ env.BUILD_DIRECTORY }} -j10
          fi

      - name: Test
        run: cd ${{ env.BUILD_DIRECTORY }} && ctest -j8 -T test --no-compress-output
