name: Build Debian Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  DOCKERFILE: docker/Dockerfile.debian
  IMAGE_WORKDIR: /mnt/workspace

jobs:
  build:
    strategy:
      matrix:
        build-type: ["debug", "release"]
        compiler: [
          { c: "gcc-11", cxx: "g++-11", package: "gcc-11 g++-11" },
          { c: "clang-14", cxx: "clang++-14", package: "clang-14" }
        ]
    runs-on: ubuntu-latest
    name: Build Debian ${{ matrix.build-type }} / ${{ matrix.compiler.cxx }}
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Build and Test
        run: |
          export BUILD_IMAGE=libcore-${{ matrix.build-type }}
          export BUILD_DIRECTORY=build/${{ matrix.build-type }}
          docker build -t $BUILD_IMAGE:latest -f ${{ env.DOCKERFILE }} .
          docker run --rm -v $(pwd):${{ env.IMAGE_WORKDIR }} $BUILD_IMAGE:latest sh -c " \
            cmake -S . -B $BUILD_DIRECTORY \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_C_COMPILER=${{ matrix.compiler.c }} \
              -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}
            cmake --build $BUILD_DIRECTORY -j10
            cd $BUILD_DIRECTORY && ctest -j8 -T test --no-compress-output
          "
