name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [DEBUG, RELEASE]
    name: Build & Test <${{ matrix.build-type }}>
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Install dependencies
        run: sudo apt-get install -y g++ cmake build-essential checkinstall zlib1g-dev libssl-dev

      - name: Build
        run: |
          if [ "${{matrix.build-type}}" == "DEBUG" ]; then
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build -j10
          else
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j10
          fi

      - name: Test
        run: cd build && ctest -j8 -T test --no-compress-output

      - name: doxygen
        run: cmake --build build --target doxygen -- --no-print-directory

  doxygen-check:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Install dependencies
        run: sudo apt-get install -y g++ cmake build-essential checkinstall zlib1g-dev libssl-dev doxygen graphviz

      - name: Check doxygen
        run: cmake --build build --target doxygen -- --no-print-directory

  clang-format-check:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Install dependencies
        run: sudo apt-get install -y clang-format 

      - name: Check clang-format
        run: |
          FILES=$(find . -name '*.cc' -o -name '*.c' -o -name '*.h')
          for file in $FILES; do
            clang-format -style=file $file > formatted_file
            if ! diff $file formatted_file > /dev/null; then
              echo "Clang-format failed on $file"
              exit 1
            fi
          done
