name: Clang-format Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  BUILD_DEPENDENCIES: build-essential checkinstall zlib1g-dev libssl-dev
  BUILD_DIRECTORY: build

jobs:
  clang-format-check:
    name: Clang-format Check
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} clang-14

      - name: Check clang-format
        run: |
          FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
          TMPFILE="./formatted_file"
          for file in $FILES; do
            clang-format -style=file $file > $TMPFILE
            if ! diff $file $TMPFILE > /dev/null; then
              echo "Clang-format failed on $file"
              rm $TMPFILE
              exit 1
            fi 
            rm $TMPFILE
          done
          echo "Clang-format check successful"
