name: Clang-format Check Pipeline

on:
  workflow_run:
    workflows: ["Build Pipeline"]
    types:
      - completed
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - '*'

env:
  BUILD_DEPENDENCIES: g++ cmake build-essential checkinstall zlib1g-dev libssl-dev
  BUILD_DIRECTORY: build

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    name: Clang-format Check
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Install dependencies
        run: sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} doxygen graphviz

      - name: Check clang-format
        run: |
          FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
          TMPFILE="./formatted_file"
          for file in $FILES; do
            clang-format -style=file $file > $TMPFILE
            if ! diff $file $TMPFILE > /dev/null; then
              echo "Clang-format failed on $file"
              rm $TMPFILE
              exit 1
            fi 
            rm $TMPFILE
          done
          echo "Clang-format check successful"
