name: Check Clang-format Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

env:
  DOCKERFILE: docker/Dockerfile.linux
  DOCKER_BUILDIMAGE: libcore-linux
  DOCKER_BUILDIMAGE_WORKDIR: /mnt/workspace

jobs:
  clang-format-check:
    name: Clang-format Check
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: Build docker image
        run: |
          docker build -t ${{ env.DOCKER_BUILDIMAGE }}:latest -f ${{ env.DOCKERFILE }} .

      - name: Check clang-format
        run: |
          docker run --rm -v $(pwd):${{ env.DOCKER_BUILDIMAGE_WORKDIR }} ${{ env.DOCKER_BUILDIMAGE }}:latest sh -c " \
            FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
            TMPFILE="./formatted_file"
            for file in $FILES; do
              sudo clang-format -style=file $file > $TMPFILE
              if ! diff $file $TMPFILE > /dev/null; then
                echo "Clang-format failed on $file"
                sudo rm $TMPFILE
                exit 1
              fi 
              sudo rm $TMPFILE
            done
          "
          echo "Clang-format check successful"
