name: Doxygen Generate and Upload

on:
  workflow_dispatch:

env:
  BUILD_DEPENDENCIES: cmake build-essential checkinstall zlib1g-dev libssl-dev libfmt-dev
  BUILD_DIRECTORY: build

jobs:
  doxygen-deploy:
    name: Doxygen Deployment
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }} clang-14 doxygen graphviz

      - name: Generate doxygen
        env:
          CC: clang
          CXX: clang++
        run: |
          cmake -S . -B ${{ env.BUILD_DIRECTORY }} -DCMAKE_BUILD_TYPE=Debug -DDOXYGEN_BUILD_ENABLED=ON
          cmake --build ${{ env.BUILD_DIRECTORY }} --target doxygen -- --no-print-directory
          doxygen ${{ env.BUILD_DIRECTORY }}/doxygen/Doxyfile

      - name: Upload Doxygen Artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: ${{ env.BUILD_DIRECTORY }}/doxygen/docs/html
          if-no-files-found: error
